version: "3.8"

services:
  ocds-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocds-scanner
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ocds-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

networks:
  ocds-network:
    driver: bridge
